[package]
name = "barkeep"
version = "0.1.0"
authors = ["kladd"]
edition = "2018"

[dependencies]
actix-web = "1.0"
actix-files = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.5"